name: 'My Action'
description: 'My first action with docker'
inputs:
  first-name:
    description: 'The first name'
    required: true
    default: 'John'
outputs:
  time:
    description: 'The elapsed time'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.first-name }}
