name: 'My Action'
description: 'My first action with docker'
inputs:
  FIRST_NAME:
    description: 'The first name'
    required: true
    default: 'John'
outputs:
  time:
    description: 'The elapsed time'
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.FIRST_NAME }}
